ideal_w1024_series :
	rm -f ideal-w1024-*.png
	ln -s ideal_black_w1024.png ideal-w1024-001.png
	ln -s ideal_black_w1024.png ideal-w1024-002.png
	ln -s ideal_black_w1024.png ideal-w1024-003.png
	ln -s ideal_black_w1024.png ideal-w1024-004.png
	ln -s ideal_white_w1024.png ideal-w1024-005.png

help :
	echo "ideal_w1024_series"
